### ISSUE TITLE
Idea: Have one row for Recall Knowledge and the roll buttons for the proficiency

### ISSUE THREAD

**Issue by jamespdaily** [jamespdaily/pf2e-sheet-skill-actions#48]
Recall Knowledge (1A):
|Society +0| |Occultism +4| (etc...)

@andriusch what ya think?

**Comment by andriusch** [comment]
I was thinking something like that too, I really like that idea, especially for exploration/downtime actions, but there are several problems with it:
1. It breaks consistency. Most of the actions have prefix "Skill Name: Action Name" and it would be weird to have some that don't have it. Maybe we could remove the prefix, but my players do find prefix useful. Perhaps it could be solved by still allowing filtering to work by skill name? Or have separate filter by skill (though I'm not sure where to put it)?
2. Specifically for "Recall knowledge" - PF2e has separate entries for each skill in compendium (if I remember correctly that's the only action that does, other multi skill actions don't have separate entries). So which one do we choose to use as main one (in terms of choosing action name & posting skill to chat when icon is clicked)? I'm leaning towards "Recall Knowledge (Lore)" since it sounds to be like the most generic one.

**Comment by andriusch** [comment]
Great, that only leaves problem 1. What do you think @jamespdaily ?

**Comment by jamespdaily** [comment]
Well one option is to remove the prefix and put it in the actual buttons so:

```
Athletics: Trip
Roll +3 | MAP -5 | MAP - 10

would become

Trip
Athletics + 3 | MAP - 5 | MAP-10 
```

Alternatively we could just make an exception for Recall Knowledge, similar to how Create a Diversion is set up

**Comment by andriusch** [comment]
I like putting skill into buttons. It's not only recall knowledge, there's identify magic, learn a spell and some others I don't remember now.
